name: Upload Python Package to PyPI

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-publish:
    name: Build and publish package
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install build tools
        run: |
          pip install build twine

      - name: Build package
        run: python -m build

      - name: Publish to PyPI
      
        run: twine upload dist/*
